language: generic 

#super user level permissions
sudo: required

services:
  - docker
#Pre-setup 
before-install:
  - docker build -t frontend -f Dockerfile.dev .
script:
  - docker run -e CI=true frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-753726523976"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


